name: fernand_env
channels:
  - conda-forge
dependencies:
  - keras
  - jupyter-server-proxy
  - tensorflow[version='>=2.0']
  - cartopy
  - scikit-learn
  - pandas
  - jupyterlab
  - seaborn
  - matplotlib
  - jupyter
  - jupytext
  - python=3.6
  - netcdf4
  - regionmask
  - xarray
  - geopandas
